#!/bin/bash
# WSS Shadowsocks Plugin - 文件索引和说明

echo "=========================================="
echo "WSS Shadowsocks Plugin - 文件列表"
echo "=========================================="
echo ""

echo "【核心程序文件】"
echo "  wss_plugin_client.py   - 客户端插件程序 (可执行)"
echo "  wss_plugin_server.py   - 服务端插件程序 (可执行)"
echo "  obfuscator.py          - 数据加扰模块 (可独立测试)"
echo ""

echo "【配置示例文件】"
echo "  config_client_example.json - 客户端配置示例"
echo "  config_server_example.json - 服务端配置示例"
echo "  test_client.sh             - 客户端测试脚本"
echo "  test_server.sh             - 服务端测试脚本"
echo ""

echo "【文档文件】"
echo "  使用说明.md            - 中文快速使用指南 ⭐ 推荐首先阅读"
echo "  README_wss_plugin.md   - 完整英文文档"
echo "  QUICKSTART.md          - 快速入门指南（英文）"
echo "  PROJECT_SUMMARY.md     - 项目总结文档"
echo "  FILES.sh               - 本文件"
echo ""

echo "【原有文件】"
echo "  client.py              - 原有 WebSocket 客户端示例"
echo "  server.py              - 原有 WebSocket 服务端示例"
echo "  websockets/            - WebSocket 库目录"
echo "  Cloak/                 - Cloak 参考项目"
echo ""

echo "=========================================="
echo "快速测试命令："
echo "=========================================="
echo ""
echo "1. 测试加扰模块："
echo "   python3 obfuscator.py"
echo ""
echo "2. 生成测试证书："
echo "   openssl req -x509 -newkey rsa:4096 -nodes \\"
echo "     -keyout privkey.pem -out fullchain.pem -days 365 \\"
echo "     -subj '/CN=localhost'"
echo ""
echo "3. 启动服务端测试："
echo "   ./test_server.sh"
echo ""
echo "4. 启动客户端测试（另开终端）："
echo "   ./test_client.sh"
echo ""
echo "=========================================="
echo "详细使用说明请查看: 使用说明.md"
echo "=========================================="
